apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-website-content
  namespace: simple-website
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Simple Website</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          margin: 0;
          padding: 20px;
          color: #333;
        }
        h1 {
          color: #2c3e50;
        }
        .container {
          max-width: 800px;
          margin: 0 auto;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Welcome to Simple Website!</h1>
        <p>This website is being served from a Kubernetes cluster using GitOps with Flux.</p>
        <p>Last updated: $(date)</p>
      </div>
    </body>
    </html> 