apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
  namespace: simple-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: simple-website
        image: ghcr.io/GITHUB_USERNAME/simple-website:latest # Replace GITHUB_USERNAME with your GitHub username
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: simple-website
  namespace: simple-website
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: simple-website
  type: ClusterIP 